metadata:
  # https://github.com/ioos/ioosngdac/wiki/NGDAC-NetCDF-File-Format-Version-2
  acknowledgement: Funding from Voice of the Ocean
  comment:        "Test processing"
  contributor_name: Callum Rollo
  contributor_role: Data processor
  creator_email: c.rollo@outlook.com
  creator_name:  Callum Rollo
  creator_url:   callumrollo.com
  # date_created etc: added automatically
  # numbers must be eenclosed by strings so YAML keeps as strings
  deployment_id: '22'
  deployment_name: 'test_mission'
  deployment_start: '2021-08-23'
  deployment_end: '2021-08-25'
  format_version: IOOS_Glider_NetCDF_v2.0.nc
  # id filled automatically...
  glider_name: voto_glider
  glider_serial: '063'
  glider_model: SeaExplorer
  glider_instrument_name: seaexplorer
  glider_wmo: '999999'
  institution: VOTO
  keywords: "AUVS, Autonomous Underwater Vehicles, Oceans, Ocean Pressure,
             Water Pressure, Oceans, Ocean Temperature, Water Temperature,
             Oceans, Salinity/Density, Conductivity, Oceans,
             Salinity/Density, Density, Oceans, Salinity/Density, Salinity"
  keywords_vocabulary: GCMD Science Keywords
  license: "This data may be redistributed and used without restriction or
            warranty"
  metadata_link: "callumrollo.com"
  Metadata_Conventions: CF-1.6, Unidata Dataset Discovery v1.0
  naming_authority: "VOTO"
  platform_type:    "SeaExplorer Glider"
  processing_level: "Data provided as is with no expressed or implied
                     assurance of quality assurance or quality control. L0"
  project: test
  project_url: test
  publisher_email: c.rollo@outlook.com
  publisher_name:  Callum Rollo
  publisher_url:   https://voiceoftheocean.org
  references:     "created with pyglider https://github.com/c-proof/pyglider"
  sea_name:   sea name test
  source:     Observational data from a profiling glider.
  standard_name_vocabulary: CF STandard Name Table v49
  summary: mission summary test
  transmission_system: IRRIDIUM
  wmo_id: "999999"


glider_devices:
  pressure:
    make: Micron
    model: Pressure
    serial: '104702'
  ctd:
    make: RBR
    model: legato
    serial: '206523'
    long_name: RBR legato CTD
    make_model:  RBR legato CTD
    factory_calibrated: "Yes"
    calibration_date: "2021-03-01"
    calibration_report: " "
    comment:   " "
  optics:
    make: Wetlabs
    model: FLNTU
    serial: '6661'
  oxygen:
    make: AROD_FT
    model: Optode4831
    serial: '0044'

# map between glider variables and netcdf variables.  This shouldn't
# change too much.
netcdf_variables:
  timebase:
    source: LEGATO_TEMPERATURE
  # Time and Place:
  time:
    source:        time
    long_name:     Time
    standard_name: time
    units:         seconds since 1970-01-01T00:00:00Z
    axis:          T
    observation_type: "measured"
    coordinates:   time depth latitude longitude

  latitude:
    source:       NAV_LATITUDE
    long_name:    latitude
    standard_name: latitude
    units:        degrees_north
    axis:         Y
    coordinates:   time depth latitude longitude
    conversion:   nmea2deg
    comment:     "Estimated between surface fixes"
    observation_type: measured
    platform:     platform
    reference:    WGS84
    valid_max:    "90.0"
    valid_min:    "-90.0"
    coordinate_reference_frame:  urn:ogc:crs:EPSG::4326

  longitude:
    source:       NAV_LONGITUDE
    long_name:    longitude
    standard_name: longitude
    units:        degrees_east
    axis:         X
    coordinates:  time depth latitude longitude
    conversion:   nmea2deg
    comment:     "Estimated between surface fixes"
    observation_type: measured
    platform:     platform
    reference:    WGS84
    valid_max:    "180.0"
    valid_min:    "-180.0"
    coordinate_reference_frame:  urn:ogc:crs:EPSG::4326

  heading:
    source:       Heading
    long_name:    glider heading angle
    standard_name: platform_orientation
    units:        degrees
    coordinates:  time depth latitude longitude

  pitch:
    source:       Pitch
    long_name:    glider pitch angle
    standard_name: platform_pitch_angle
    units:        degrees
    coordinates:  time depth latitude longitude

  roll:
    source:       Roll
    long_name:    glider roll angle
    standard_name: platform_roll_angle
    units:        degrees
    coordinates:  time depth latitude longitude

  # data parameters
  conductivity:
    source:       LEGATO_CONDUCTIVITY
    long_name:    water conductivity
    standard_name: sea_water_electrical_conductivity
    units:        mS cm-1
    coordinates:  time depth latitude longitude
    instrument:    instrument_ctd
    valid_min:    "0."
    valid_max:    "10."
    observation_type: "measured"
    accuracy:      "0.0003"
    precision:     "0.0001"
    resolution:     "0.00002"

  temperature:
    source:       LEGATO_TEMPERATURE
    long_name:    water temperature
    standard_name: sea_water_temperature
    units:        Celsius
    coordinates:  time depth latitude longitude
    instrument:   instrument_ctd
    valid_min:    "-5"
    valid_max:    "50"
    observation_type: "measured"
    accuracy:      "0.002"
    precision:     "0.001"
    resolution:    "0.0002"

  pressure:
    source:       LEGATO_PRESSURE
    long_name:    water pressure
    standard_name:  sea_water_pressure
    units:        dbar
    coordinates:  time depth latitude longitude
    valid_min:    "0"
    valid_max:    "2000"
    positive:      "down"
    reference_datum:  "sea-surface"
    instrument:     "instrument_ctd"
    observation_type: "measured"
    accuracy:         "1"
    precision:        "2"
    resolution:       "0.02"
    comment:          "ctd pressure sensor"

  salinity:
    source:       LEGATO_SALINITY
    long_name:    water salinity
    standard_name: sea_water_salinity
    units:        kg m-3
    coordinates:  time depth latitude longitude
    instrument:    instrument_ctd
    valid_min:    "0."
    valid_max:    "50."
    observation_type: "calculated"
    accuracy:      "0.0003"
    precision:     "0.0001"
    resolution:     "0.00002"

# optics:
  chlorophyll:
    source:       FLNTU_CHL_SCALED
    long_name:    chlorophyll
    standard_name: concentration_of_chlorophyll_in_sea_water
    units:        mg m-3
    coordinates:  time depth latitude longitude

  cdom:
    source:  FLNTU_NTU_SCALED
    long_name:    flntu variable
    units:        arbitrary
    coordinates:  time depth latitude longitude



# Oxygen
  oxygen_concentration:
    source:       AROD_FT_DO
    long_name:    oxygen concentration
    standard_name: mole_concentration_of_dissolved_molecular_oxygen_in_sea_water
    correct_oxygen: "True"
    reference_salinity: "0"
    units:        umol l-1
    coordinates:   time depth latitude longitude

  temperature_oxygen:
    source:  AROD_FT_TEMP
    long_name:    oxygen sensor temperature
    standard_name: temperature_of_sensor_for_oxygen_in_sea_water
    units:        Celsius
    coordinates:   time depth latitude longitude



# AD2CP
  ad2cp_heading:
    source:       AD2CP_HEADING
    long_name:    glider heading angle from AD2CP
    standard_name: platform_orientation_ad2cp
    units:        degrees
    coordinates:  time depth latitude longitude

  ad2cp_pitch:
    source:       AD2CP_PITCH
    long_name:    glider pitch angle from AD2CP
    standard_name: platform_pitch_angle_ad2cp
    units:        degrees
    coordinates:  time depth latitude longitude

  ad2cp_roll:
    source:       AD2CP_ROLL
    long_name:    glider roll angle from AD2CP
    standard_name: platform_roll_angle_ad2cp
    units:        degrees
    coordinates:  time depth latitude longitude

  ad2cp_time:
    source:       AD2CP_TIME
    long_name:    AD2CP recorded time
    standard_name: ad2cp_recorded_time
    coordinates:  time depth latitude longitude
    # derived water speed:
  # water_velocity_eastward:
  #   source:    m_final_water_vx
  #   long_name:      mean eastward water velocity in segment
  #   standard_name:  barotropic_eastward_sea_water_velocity
  #   units:          m s-1
  #   coordinates:   time depth latitude longitude
  #
  # water_velocity_northward:
  #   source:    m_final_water_vy
  #   long_name:      mean northward water velocity in segment
  #   standard_name:  barotropic_northward_sea_water_velocity
  #   units:          m s-1
  #   coordinates:   time depth latitude longitude

profile_variables:
  # variables for extract_L1timeseries_profiles processing step...
  profile_id:
    comment: Sequential profile number within the trajectory.  This value is unique in each file that is part of a single trajectory/deployment.
    long_name: 'Profile ID'
    valid_max: '2147483647'
    valid_min: '1'

  profile_time:
    comment:           Timestamp corresponding to the mid-point of the profile
    long_name:         Profile Center Time
    observation_type:  calculated
    platform:          platform
    standard_name:     time
    units:             seconds since 1970-01-01T00:00:00Z

  profile_time_start:
    comment:           Timestamp corresponding to the start of the profile
    long_name:         Profile Start Time
    observation_type:  calculated
    platform:          platform
    standard_name:     time
    units:             seconds since 1970-01-01T00:00:00Z

  profile_time_end:
    comment:           Timestamp corresponding to the end of the profile
    long_name:         Profile End Time
    observation_type:  calculated
    platform:          platform
    standard_name:     time
    units:             seconds since 1970-01-01T00:00:00Z

  profile_lat:
    comment:           Value is interpolated to provide an estimate of the latitude at the mid-point of the profile
    long_name:         Profile Center Latitude
    observation_type:  calculated
    platform:          platform
    standard_name:     latitude
    units:             degrees_north
    valid_max:         "90.0"
    valid_min:         "-90.0"

  profile_lon:
    comment:           Value is interpolated to provide an estimate of the latitude at the mid-point of the profile
    long_name:         Profile Center Longitude
    observation_type:  calculated
    platform:          platform
    standard_name:     longitude
    units:             degrees_east
    valid_max:         "180.0"
    valid_min:         "-180.0"

  u:
    comment:  The depth-averaged current is an estimate of the net current measured while the glider is underwater.  The value is calculated over the entire underwater segment, which may consist of 1 or more dives.
    long_name:         Depth-Averaged Eastward Sea Water Velocity
    observation_type:  calculated
    platform:          platform
    standard_name:     eastward_sea_water_velocity
    units:             m s-1
    valid_max:         "10.0"
    valid_min:         "-10.0"

  v:
    comment:  The depth-averaged current is an estimate of the net current measured while the glider is underwater.  The value is calculated over the entire underwater segment, which may consist of 1 or more dives.
    long_name:         Depth-Averaged Northward Sea Water Velocity
    observation_type:  calculated
    platform:          platform
    standard_name:     northward_sea_water_velocity
    units:             m s-1
    valid_max:         "10.0"
    valid_min:         "-10.0"

  lon_uv:
    comment:           Not computed
    long_name:         Longitude
    observation_type:  calculated
    platform:          platform
    standard_name:     longitude
    units:             degrees_east
    valid_max:         "180.0"
    valid_min:         "-180.0"

  lat_uv:
    comment:           Not computed
    long_name:         Latitude
    observation_type:  calculated
    platform:          platform
    standard_name:     latitude
    units:             degrees_north
    valid_max:         "90.0"
    valid_min:         "-90.0"

  time_uv:
    comment:       Not computed
    long_name:     Time
    standard_name: time
    calendar:      gregorian
    units:         seconds since 1970-01-01T00:00:00Z
    observation_type: calculated

  instrument_ctd:
    comment:    unpumped RBR legato CTD
    calibration_date:     "2021-03-01"
    calibration_report:  " "
    factory_calibrated:  "yes"
    long_name:           RBR legato seaexplorer CTD
    make_model:          RBR legato
    platform:            platform
    serial_number:       "206523"
    type:                platform
